export type LatamCountry = {
  code: string
  name: string
  dialCode: string
  regions: string[]
}

export const LATAM_COUNTRIES: LatamCountry[] = [
  {
    code: 'AR',
    name: 'Argentina',
    dialCode: '+54',
    regions: [
      'Buenos Aires',
      'Ciudad Autonoma de Buenos Aires',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Cordoba',
      'Corrientes',
      'Entre Rios',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquen',
      'Rio Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucuman',
    ],
  },
  {
    code: 'BO',
    name: 'Bolivia',
    dialCode: '+591',
    regions: ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosi', 'Santa Cruz', 'Tarija'],
  },
  {
    code: 'BR',
    name: 'Brasil',
    dialCode: '+55',
    regions: [
      'Acre',
      'Alagoas',
      'Amapa',
      'Amazonas',
      'Bahia',
      'Ceara',
      'Distrito Federal',
      'Espirito Santo',
      'Goias',
      'Maranhao',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Para',
      'Paraiba',
      'Parana',
      'Pernambuco',
      'Piaui',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondonia',
      'Roraima',
      'Santa Catarina',
      'Sao Paulo',
      'Sergipe',
      'Tocantins',
    ],
  },
  {
    code: 'CL',
    name: 'Chile',
    dialCode: '+56',
    regions: [
      'Arica y Parinacota',
      'Tarapaca',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaiso',
      'Metropolitana de Santiago',
      'O Higgins',
      'Maule',
      'Nuble',
      'Biobio',
      'La Araucania',
      'Los Rios',
      'Los Lagos',
      'Aysen',
      'Magallanes',
    ],
  },
  {
    code: 'CO',
    name: 'Colombia',
    dialCode: '+57',
    regions: [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlantico',
      'Bogota',
      'Bolivar',
      'Boyaca',
      'Caldas',
      'Caqueta',
      'Casanare',
      'Cauca',
      'Cesar',
      'Choco',
      'Cordoba',
      'Cundinamarca',
      'Guainia',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Narino',
      'Norte de Santander',
      'Putumayo',
      'Quindio',
      'Risaralda',
      'San Andres y Providencia',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupes',
      'Vichada',
    ],
  },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', regions: ['San Jose', 'Alajuela', 'Cartago', 'Heredia', 'Guanacaste', 'Puntarenas', 'Limon'] },
  { code: 'CU', name: 'Cuba', dialCode: '+53', regions: ['Pinar del Rio', 'La Habana', 'Mayabeque', 'Matanzas', 'Cienfuegos', 'Villa Clara', 'Sancti Spiritus', 'Ciego de Avila', 'Camaguey', 'Las Tunas', 'Holguin', 'Granma', 'Santiago de Cuba', 'Guantanamo', 'Isla de la Juventud'] },
  { code: 'DO', name: 'Republica Dominicana', dialCode: '+1', regions: ['Distrito Nacional', 'Santo Domingo', 'Santiago', 'La Vega', 'Puerto Plata', 'San Cristobal', 'Duarte', 'La Romana', 'San Pedro de Macoris', 'La Altagracia'] },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', regions: ['Azuay', 'Bolivar', 'Canar', 'Carchi', 'Chimborazo', 'Cotopaxi', 'El Oro', 'Esmeraldas', 'Galapagos', 'Guayas', 'Imbabura', 'Loja', 'Los Rios', 'Manabi', 'Morona Santiago', 'Napo', 'Orellana', 'Pastaza', 'Pichincha', 'Santa Elena', 'Santo Domingo de los Tsachilas', 'Sucumbios', 'Tungurahua', 'Zamora Chinchipe'] },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', regions: ['Ahuachapan', 'Cabanas', 'Chalatenango', 'Cuscatlan', 'La Libertad', 'La Paz', 'La Union', 'Morazan', 'San Miguel', 'San Salvador', 'San Vicente', 'Santa Ana', 'Sonsonate', 'Usulutan'] },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', regions: ['Alta Verapaz', 'Baja Verapaz', 'Chimaltenango', 'Chiquimula', 'El Progreso', 'Escuintla', 'Guatemala', 'Huehuetenango', 'Izabal', 'Jalapa', 'Jutiapa', 'Peten', 'Quetzaltenango', 'Quiche', 'Retalhuleu', 'Sacatepequez', 'San Marcos', 'Santa Rosa', 'Solola', 'Suchitepequez', 'Totonicapan', 'Zacapa'] },
  { code: 'HN', name: 'Honduras', dialCode: '+504', regions: ['Atlantida', 'Choluteca', 'Colon', 'Comayagua', 'Copan', 'Cortes', 'El Paraiso', 'Francisco Morazan', 'Gracias a Dios', 'Intibuca', 'Islas de la Bahia', 'La Paz', 'Lempira', 'Ocotepeque', 'Olancho', 'Santa Barbara', 'Valle', 'Yoro'] },
  { code: 'MX', name: 'Mexico', dialCode: '+52', regions: ['Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de Mexico', 'Coahuila', 'Colima', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico', 'Michoacan', 'Morelos', 'Nayarit', 'Nuevo Leon', 'Oaxaca', 'Puebla', 'Queretaro', 'Quintana Roo', 'San Luis Potosi', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatan', 'Zacatecas'] },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', regions: ['Boaco', 'Carazo', 'Chinandega', 'Chontales', 'Esteli', 'Granada', 'Jinotega', 'Leon', 'Madriz', 'Managua', 'Masaya', 'Matagalpa', 'Nueva Segovia', 'Rio San Juan', 'Rivas', 'Costa Caribe Norte', 'Costa Caribe Sur'] },
  { code: 'PA', name: 'Panama', dialCode: '+507', regions: ['Bocas del Toro', 'Chiriqui', 'Cocle', 'Colon', 'Darien', 'Herrera', 'Los Santos', 'Panama', 'Panama Oeste', 'Veraguas'] },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', regions: ['Alto Paraguay', 'Alto Parana', 'Amambay', 'Asuncion', 'Boqueron', 'Caaguazu', 'Caazapa', 'Canindeyu', 'Central', 'Concepcion', 'Cordillera', 'Guaira', 'Itapua', 'Misiones', 'Neembucu', 'Paraguari', 'Presidente Hayes', 'San Pedro'] },
  { code: 'PE', name: 'Peru', dialCode: '+51', regions: ['Amazonas', 'Ancash', 'Apurimac', 'Arequipa', 'Ayacucho', 'Cajamarca', 'Callao', 'Cusco', 'Huancavelica', 'Huanuco', 'Ica', 'Junin', 'La Libertad', 'Lambayeque', 'Lima', 'Loreto', 'Madre de Dios', 'Moquegua', 'Pasco', 'Piura', 'Puno', 'San Martin', 'Tacna', 'Tumbes', 'Ucayali'] },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1', regions: ['San Juan', 'Bayamon', 'Carolina', 'Ponce', 'Caguas', 'Guaynabo', 'Mayaguez', 'Arecibo'] },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', regions: ['Artigas', 'Canelones', 'Cerro Largo', 'Colonia', 'Durazno', 'Flores', 'Florida', 'Lavalleja', 'Maldonado', 'Montevideo', 'Paysandu', 'Rio Negro', 'Rivera', 'Rocha', 'Salto', 'San Jose', 'Soriano', 'Tacuarembo', 'Treinta y Tres'] },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', regions: ['Amazonas', 'Anzoategui', 'Apure', 'Aragua', 'Barinas', 'Bolivar', 'Carabobo', 'Cojedes', 'Delta Amacuro', 'Distrito Capital', 'Falcon', 'Guarico', 'Lara', 'Merida', 'Miranda', 'Monagas', 'Nueva Esparta', 'Portuguesa', 'Sucre', 'Tachira', 'Trujillo', 'Vargas', 'Yaracuy', 'Zulia'] },
]

export const PHONE_COUNTRIES: LatamCountry[] = [
  { code: 'US', name: 'Estados Unidos', dialCode: '+1', regions: [] },
  ...LATAM_COUNTRIES,
]

export function getCountry(code: string | undefined, source = LATAM_COUNTRIES) {
  return source.find((country) => country.code === code) || source[0]
}

export function flagUrl(countryCode: string) {
  return `https://flagcdn.com/24x18/${countryCode.toLowerCase()}.png`
}
